export const SAVANNA_VAULT_ABI = [
  // ERC-4626
  "function asset() external view returns (address)",
  "function totalAssets() external view returns (uint256)",
  "function totalSupply() external view returns (uint256)",
  "function balanceOf(address account) external view returns (uint256)",
  "function convertToAssets(uint256 shares) external view returns (uint256)",
  "function convertToShares(uint256 assets) external view returns (uint256)",
  "function maxDeposit(address) external view returns (uint256)",
  "function deposit(uint256 assets, address receiver) external returns (uint256 shares)",
  "function maxWithdraw(address) external view returns (uint256)",
  "function withdraw(uint256 assets, address receiver, address owner) external returns (uint256 shares)",
  "function maxMint(address) external view returns (uint256)",
  "function mint(uint256 shares, address receiver) external returns (uint256 assets)",
  "function maxRedeem(address owner) external view returns (uint256)",
  "function redeem(uint256 shares, address receiver, address owner) external returns (uint256 assets)",
  // SavannaVault
  "function controller() external view returns (address)",
  "function crossChainReceiver() external view returns (address)",
  "function oracle() external view returns (address)",
  "function totalDeployed() external view returns (uint256)",
  "function totalPositions() external view returns (uint256)",
  "function totalCrossChainDeposits() external view returns (uint256)",
  "function totalYieldEarned() external view returns (uint256)",
  "function lastRebalance() external view returns (uint256)",
  "function rebalanceInterval() external view returns (uint256)",
  "function requestStrategy(uint256 timeHorizon) external",
  "function cancelTimedOutRequest() external",
  "function crossChainDeposit(uint256 assets, address receiver, uint256 sourceChainId, address bridgeToken) external returns (uint256 shares)",
  "function getUserPosition(address user) external view returns (tuple(uint256 depositAmount, uint256 timeHorizon, uint256 depositTimestamp, address activeStrategy, uint256 allocatedAmount, bool isActive))",
  "function getCrossChainDeposit(uint256 index) external view returns (tuple(address depositor, uint256 sourceChainId, uint256 amount, uint256 timestamp, address bridgeToken, bool processed))",
  "function hasActiveRequest(address user) external view returns (bool)",
  "function getAssetPriceUsd() external view returns (uint256)",
  "function getUserPositionValueUsd(address user) external view returns (uint256)",
  "function getTotalDeployedValueUsd() external view returns (uint256)",
  "function setController(address controller) external",
  "function setCrossChainReceiver(address receiver) external",
  "function setOracle(address oracle) external",
  "function setRebalanceInterval(uint256 interval) external",
  "function pause() external",
  "function unpause() external",
  "function checkUpkeep(bytes calldata) external view returns (bool upkeepNeeded, bytes memory performData)",
  "function performUpkeep(bytes calldata performData) external",
  "event Deposited(address indexed user, uint256 amount, uint256 shares)",
  "event StrategyRequested(address indexed user, uint256 depositAmount, uint256 timeHorizon, uint256 timestamp)",
  "event StrategyExecuted(address indexed user, address strategy, uint256 amount)",
  "event StrategyCompleted(address indexed user, uint256 returnedAmount)",
  "event Withdrawn(address indexed user, uint256 amount, uint256 shares)",
  "event CrossChainDepositReceived(address indexed depositor, uint256 sourceChainId, uint256 amount, address bridgeToken, uint256 shares)",
  "event YieldEarned(address indexed user, int256 yieldAmount, uint256 returnedAmount, uint256 allocatedAmount)",
  "event RebalanceTriggered(uint256 indexed timestamp, uint256 positionsProcessed)",
  "event OracleUpdated(address indexed oldOracle, address indexed newOracle)",
] as const;

export const SAVANNA_CONTROLLER_ABI = [
  "function vault() external view returns (address)",
  "function forwarder() external view returns (address)",
  "function totalRecommendations() external view returns (uint256)",
  "function strategies(uint8 protocol) external view returns (address)",
  "function priceFeeds(address asset) external view returns (address)",
  "function getStrategy(uint8 protocol) external view returns (address)",
  "function getLatestPrice(address asset) external view returns (int256 price)",
  "function withdrawFromStrategy(address user) external",
  "function onReport(bytes calldata metadata, bytes calldata report) external",
  "function rebalance() external view",
  "function setStrategy(uint8 protocol, address strategy) external",
  "function setForwarder(address forwarder) external",
  "function setPriceFeed(address asset, address feed) external",
  "event StrategyUpdated(uint8 indexed protocol, address indexed strategy)",
  "event RecommendationReceived(address indexed user, uint8 protocol, uint256 allocationBps, uint256 expectedApy, string reasoning)",
  "event StrategyExecuted(address indexed user, address strategy, uint256 amount)",
  "event UserWithdrawn(address indexed user, uint256 amount)",
  "event ForwarderUpdated(address indexed oldForwarder, address indexed newForwarder)",
] as const;

export const SAVANNA_ORACLE_ABI = [
  "function owner() external view returns (address)",
  "function assetFeeds(address asset) external view returns (address)",
  "function isSupportedAsset(address asset) external view returns (bool)",
  "function STALENESS_THRESHOLD() external view returns (uint256)",
  "function CELO_USD_FEED() external view returns (address)",
  "function USDC_USD_FEED() external view returns (address)",
  "function getAssetPrice(address asset) external view returns (uint256)",
  "function getAssetValueUsd(address asset, uint256 amount) external view returns (uint256)",
  "function getValidatedRoundData(address feed) external view returns (uint80 roundId, int256 answer, uint256 updatedAt)",
  "function setAssetFeed(address asset, address feed) external",
  "function setAssetSupport(address asset, bool supported) external",
  "event AssetFeedUpdated(address indexed asset, address indexed feed)",
  "event AssetSupportUpdated(address indexed asset, bool supported)",
] as const;

export const ERC20_ABI = [
  "function balanceOf(address account) external view returns (uint256)",
  "function allowance(address owner, address spender) external view returns (uint256)",
  "function approve(address spender, uint256 amount) external returns (bool)",
  "function decimals() external view returns (uint8)",
  "function symbol() external view returns (string)",
  "function name() external view returns (string)",
] as const;

export const SAVANNA_FUNCTIONS_CONSUMER_ABI = [
  "function controller() external view returns (address)",
  "function vault() external view returns (address)",
  "function subscriptionId() external view returns (uint64)",
  "function callbackGasLimit() external view returns (uint32)",
  "function donId() external view returns (bytes32)",
  "function sourceCode() external view returns (string)",
  "function pendingRequests(bytes32 requestId) external view returns (address)",
  "function requestTimeHorizons(bytes32 requestId) external view returns (uint256)",
  "function totalRequestsSent() external view returns (uint256)",
  "function totalResponsesReceived() external view returns (uint256)",
  "function requestAIStrategy(address user, uint256 timeHorizon) external returns (bytes32 requestId)",
  "function getPendingRequest(bytes32 requestId) external view returns (address user, uint256 timeHorizon)",
  "function setSourceCode(string calldata newSource) external",
  "function setSubscriptionId(uint64 newSubId) external",
  "function setDonId(bytes32 newDonId) external",
  "function setController(address newController) external",
  "function setCallbackGasLimit(uint32 newLimit) external",
  "event AIRequestSent(bytes32 indexed requestId, address indexed user, uint256 timeHorizon)",
  "event AIResponseReceived(bytes32 indexed requestId, address indexed user, uint8 protocol, uint256 allocationBps, uint256 expectedApy, uint8 riskScore)",
  "event AIRequestFailed(bytes32 indexed requestId, string reason)",
  "event SourceCodeUpdated()",
  "event SubscriptionUpdated(uint64 oldSubId, uint64 newSubId)",
  "event DonIdUpdated(bytes32 oldDonId, bytes32 newDonId)",
  "event ControllerUpdated(address oldController, address newController)",
  "event CallbackGasLimitUpdated(uint32 oldLimit, uint32 newLimit)",
] as const;

export const MENTO_SAVINGS_STRATEGY_ABI = [
  // BaseStrategy (inherited)
  "function vault() external view returns (address)",
  "function controller() external view returns (address)",
  "function ASSET() external view returns (address)",
  "function active() external view returns (bool)",
  "function deposit(address asset, uint256 amount) external",
  "function withdraw(address asset, uint256 amount, address recipient) external returns (uint256 withdrawn)",
  "function getBalance(address asset) external view returns (uint256 balance)",
  // MentoSavingsStrategy
  "function MENTO_SAVINGS_TOKEN() external view returns (address)",
  "function protocolName() external pure returns (string memory)",
  "function getApy() external view returns (uint256)",
  // BaseStrategy admin
  "function setVault(address vault_) external",
  "function setController(address controller_) external",
  "function setActive(bool active_) external",
  "function emergencyWithdraw(address asset, uint256 amount, address recipient) external",
  // Events
  "event Deposited(address indexed asset, uint256 amount)",
  "event Withdrawn(address indexed asset, uint256 amount, address recipient)",
  "event YieldHarvested(address indexed asset, uint256 amount)",
] as const;

/** Mento Savings Token (sCU / sCE) — ERC-4626 savings vault on Celo */
export const MENTO_SAVINGS_TOKEN_ABI = [
  // ERC-4626
  "function asset() external view returns (address)",
  "function totalAssets() external view returns (uint256)",
  "function totalSupply() external view returns (uint256)",
  "function balanceOf(address account) external view returns (uint256)",
  "function convertToAssets(uint256 shares) external view returns (uint256)",
  "function convertToShares(uint256 assets) external view returns (uint256)",
  "function deposit(uint256 assets, address receiver) external returns (uint256 shares)",
  "function withdraw(uint256 assets, address receiver, address owner) external returns (uint256 shares)",
  "function maxDeposit(address) external view returns (uint256)",
  "function maxWithdraw(address owner) external view returns (uint256)",
  // Mento-specific
  "function savingsRate() external view returns (uint256)",
  "function exchangeRate() external view returns (uint256)",
  // ERC-20
  "function decimals() external view returns (uint8)",
  "function symbol() external view returns (string)",
  "function name() external view returns (string)",
] as const;

export const CROSS_CHAIN_RECEIVER_ABI = [
  "function VAULT() external view returns (address)",
  "function VAULT_ASSET() external view returns (address)",
  "function totalCrossChainDeposits() external view returns (uint256)",
  "function totalCrossChainVolume() external view returns (uint256)",
  "function allowedSourceChains(uint256 chainId) external view returns (bool)",
  "function supportedBridgeTokens(address token) external view returns (bool)",
  "function receiveCrossChainDeposit(address depositor, uint256 sourceChainId, address bridgeToken, uint256 amount) external returns (uint256 shares)",
  "function getCrossChainDeposit(uint256 index) external view returns (tuple(address depositor, uint256 sourceChainId, uint256 amount, uint256 timestamp, address bridgeToken, bool processed))",
  "function getUserCrossChainDeposits(address user) external view returns (uint256[] memory)",
  "function getUserCrossChainDepositCount(address user) external view returns (uint256)",
  "function setSourceChain(uint256 chainId, bool allowed) external",
  "function setSourceChains(uint256[] chainIds, bool allowed) external",
  "function setBridgeToken(address token, bool supported) external",
  "function pause() external",
  "function unpause() external",
  "event SourceChainUpdated(uint256 indexed chainId, bool allowed)",
  "event BridgeTokenUpdated(address indexed token, bool supported)",
  "event DepositReceived(address indexed depositor, uint256 indexed sourceChainId, uint256 amount, address bridgeToken, uint256 vaultShares)",
] as const;
